# Generated by Django 5.2.8 on 2025-11-13 18:02

import ChatHiveApp.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('DIRECT', 'Direct'), ('GROUP', 'Group')], db_index=True, max_length=12)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('direct_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('TEXT', 'Text'), ('FILE', 'File'), ('SYSTEM', 'System')], db_index=True, default='TEXT', max_length=10)),
                ('text', models.TextField(blank=True, default='')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('client_id', models.CharField(blank=True, help_text='Idempotency key from client', max_length=64, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='ChatHiveApp.message')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ChatHiveApp.thread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadMember',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('last_read_message_id', models.UUIDField(blank=True, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='ChatHiveApp.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=ChatHiveApp.models.attachment_upload_to)),
                ('storage_key', models.CharField(blank=True, default='', max_length=300)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, default='', max_length=64)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ChatHiveApp.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='ChatHiveApp_message_19d461_idx'), models.Index(fields=['mime'], name='ChatHiveApp_mime_497ec3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageAudit',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('EDIT', 'Edit'), ('DELETE', 'Delete')], max_length=10)),
                ('old_text', models.TextField(blank=True, default='')),
                ('new_text', models.TextField(blank=True, default='')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ChatHiveApp.message')),
            ],
            options={
                'indexes': [models.Index(fields=['message', 'event'], name='ChatHiveApp_message_7e43da_idx'), models.Index(fields=['created_at'], name='ChatHiveApp_created_cfca1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('emoji', models.CharField(max_length=32)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='ChatHiveApp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['message'], name='ChatHiveApp_message_2d3fed_idx'), models.Index(fields=['user'], name='ChatHiveApp_user_id_6f62b4_idx')],
                'constraints': [models.UniqueConstraint(fields=('message', 'user', 'emoji'), name='uniq_reaction_per_user_per_emoji')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DELIVERED', 'Delivered'), ('READ', 'Read')], db_index=True, default='DELIVERED', max_length=12)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='ChatHiveApp.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='ChatHiveApp_user_id_87d663_idx'), models.Index(fields=['message', 'status'], name='ChatHiveApp_message_08d905_idx')],
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['kind', 'is_archived'], name='ChatHiveApp_kind_7ca492_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['-last_message_at'], name='ChatHiveApp_last_me_c1631a_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created_at'], name='ChatHiveApp_thread__26e35f_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='ChatHiveApp_sender__64d3b4_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['type'], name='ChatHiveApp_type_347ec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('client_id__isnull', False)), fields=('thread', 'client_id'), name='uniq_message_thread_client_id_not_null'),
        ),
        migrations.AddIndex(
            model_name='threadmember',
            index=models.Index(fields=['user', 'is_active'], name='ChatHiveApp_user_id_87011b_idx'),
        ),
        migrations.AddIndex(
            model_name='threadmember',
            index=models.Index(fields=['thread', 'role'], name='ChatHiveApp_thread__57056d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadmember',
            unique_together={('thread', 'user')},
        ),
    ]
