# Generated by Django 5.2.8 on 2025-11-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatHiveApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='direct_key',
            field=models.CharField(blank=True, db_index=True, help_text="Clave determinística para hilos DIRECT (p.ej. '<user1>:<user2>').", max_length=128, null=True, unique=True),
        ),
    ]
